export const collection = [
  {
    name: "𝔊𝔥𝔬𝔰𝔱 25",
    description: "Don't be afraid. I'm a good ghost.",
    contract: "KT1CMhjdDMUi9LEXMBpZ9htunf6SUtP1HeHU",
    creator_address: "tz1NvTU7yGsVKZn2svBXZDRkFEnBjq7yMbPj",
    token: "24",
    creator_name: "Tez Ghosts",
    image:
      "https://assets.objkt.media/file/assets-003/QmUaNBx3W5jwHPbqYN46FxQqNBxvwysUGJqTV32WfsmE2p/artifact",
    is_darkblocked: false,
  },
  {
    name: "𝔊𝔥𝔬𝔰𝔱 31",
    description: "Don't be afraid. I'm a good ghost",
    contract: "KT1CMhjdDMUi9LEXMBpZ9htunf6SUtP1HeHU",
    creator_address: "tz1NvTU7yGsVKZn2svBXZDRkFEnBjq7yMbPj",
    token: "30",
    creator_name: "Tez Ghosts",
    image:
      "https://assets.objkt.media/file/assets-003/QmRke4H9e1Z7nLbxtVLEcRJWSMSUv5jL9jgHVrsKDp9pir/artifact",
    is_darkblocked: false,
  },
	{
		name: "Coming Up - Ram Darr",
		description: "Coming Up - Ram DarrSingle",
		contract: "KT1EpGgjQs73QfFJs9z7m1Mxm5MTnpC2tqse",
		creator_address: "tz1PdtTsGewZzcnf9ZMjbaiZhEPEDb8BoC78",
		token: "81721",
		creator_name: null,
		image: "https://ipfs.io/ipfs/QmUwKkiNQJr787tdjXNTkJR5WdvhxXYGxrpZyJKCM8HNQ7",
		is_darkblocked: false,
	},
  {
    name: "𝔊𝔥𝔬𝔰𝔱 13",
    description: "Don't be afraid. I'm a good ghost",
    contract: "KT1CMhjdDMUi9LEXMBpZ9htunf6SUtP1HeHU",
    creator_address: "tz1NvTU7yGsVKZn2svBXZDRkFEnBjq7yMbPj",
    token: "12",
    creator_name: "Tez Ghosts",
    image:
      "https://assets.objkt.media/file/assets-003/QmeGCi7adJsd3ytCtg3G3NsPRCPB3xKT4SrgY8JTRiXgMd/artifact",
    is_darkblocked: false,
  },
	{
    name: "Coming Up - Ram Darr",
    description: "Coming Up - Ram DarrSingle",
    creator_name: null,
    creator_address: "tz1PdtTsGewZzcnf9ZMjbaiZhEPEDb8BoC78",
    owner_name: null,
    contract: "KT1EpGgjQs73QfFJs9z7m1Mxm5MTnpC2tqse",
    token: "81720",
    image: "https://ipfs.io/ipfs/QmUwKkiNQJr787tdjXNTkJR5WdvhxXYGxrpZyJKCM8HNQ7",
    platform: "Tezos",
    is_darkblocked: false,
	},
	{
    name: "Whirlpool 01",
    description: "Whirlpool 01 is the first NFT of the Whirlpool Collection",
    creator_name: null,
    creator_address: "tz1PdtTsGewZzcnf9ZMjbaiZhEPEDb8BoC78",
    owner_name: null,
    owner_address: "tz1PdtTsGewZzcnf9ZMjbaiZhEPEDb8BoC78",
    contract: "KT18pVpRXKPY2c4U2yFEGSH3ZnhB2kL8kwXS",
    token: "41534",
    image: "https://ipfs.io/ipfs/QmXeTVvmqVkkGMdvzTM834jXUkoSczyNJyH6uLgNJW4dRb/image.png",
    blockchain: "TZIP-12",
    is_darkblocked: true,
	},
  {
    name: "𝔊𝔥𝔬𝔰𝔱 32",
    description: "Don't be afraid. I'm a good ghost",
    contract: "KT1CMhjdDMUi9LEXMBpZ9htunf6SUtP1HeHU",
    creator_address: "tz1NvTU7yGsVKZn2svBXZDRkFEnBjq7yMbPj",
    token: "31",
    creator_name: "Tez Ghosts",
    image:
      "https://assets.objkt.media/file/assets-003/QmS8KqfPAE7SK5xqepfp69tBpFjuswu8xPi7Nf4NLVAqK7/artifact",
    is_darkblocked: false,
  },
  {
    name: "𝔊𝔥𝔬𝔰𝔱 29",
    description: "Don't be afraid. I'm a good ghost",
    contract: "0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d",
    creator_address: "tz1NvTU7yGsVKZn2svBXZDRkFEnBjq7yMbPj",
    token: "28",
    creator_name: "Tez Ghosts",
    image:
      "https://assets.objkt.media/file/assets-003/QmQFH3LuaPwJ7FZt4jtUSBtuf35EYCd4XLGujbH5D5eT4B/artifact",
    is_darkblocked: false,
  },
  {
    name: "𝔊𝔥𝔬𝔰𝔱 30",
    description: "Don't be afraid. I'm a good ghost",
    contract: "KT1CMhjdDMUi9LEXMBpZ9htunf6SUtP1HeHU",
    creator_address: "tz1NvTU7yGsVKZn2svBXZDRkFEnBjq7yMbPj",
    token: "29",
    creator_name: "Tez Ghosts",
    image:
      "https://assets.objkt.media/file/assets-003/QmdigQ2sePnnXCU3wJb84LjvHKbNLDd2UjgKQE6Pk8w2VY/artifact",
    is_darkblocked: false,
  },
  {
    name: "𝔊𝔥𝔬𝔰𝔱 28",
    description: "Don't be afraid. I'm a good ghost",
    contract: "KT1CMhjdDMUi9LEXMBpZ9htunf6SUtP1HeHU",
    creator_address: "tz1NvTU7yGsVKZn2svBXZDRkFEnBjq7yMbPj",
    token: "27",
    creator_name: "Tez Ghosts",
    image:
      "https://assets.objkt.media/file/assets-003/QmXkw38Aj5YBRA77LQws77vaWYsBZcofcMHnCttu3zGo6v/artifact",
    is_darkblocked: false,
  },
  {
    name: "𝔊𝔥𝔬𝔰𝔱 27",
    description: "Don't be afraid. I'm a good ghost",
    contract: "KT1CMhjdDMUi9LEXMBpZ9htunf6SUtP1HeHU",
    creator_address: "tz1NvTU7yGsVKZn2svBXZDRkFEnBjq7yMbPj",
    token: "26",
    creator_name: "Tez Ghosts",
    image:
      "https://assets.objkt.media/file/assets-003/QmZxfzhcCXJVJupg9KcbydsPEJC87K8Tc8H9PLZWd6xSQM/artifact",
    is_darkblocked: false,
  },
  {
    name: "𝔊𝔥𝔬𝔰𝔱 26",
    description: "Don't be afraid. I'm a good ghost",
    contract: "KT1CMhjdDMUi9LEXMBpZ9htunf6SUtP1HeHU",
    creator_address: "tz1NvTU7yGsVKZn2svBXZDRkFEnBjq7yMbPj",
    token: "25",
    creator_name: "Tez Ghosts",
    image:
      "https://assets.objkt.media/file/assets-003/QmcHGXkKJR1uN3B38rxftLDLubyP7Zjq659fi4JrWeYyer/artifact",
    is_darkblocked: false,
  },
  {
    name: "Chaos of the Metaverse",
    contract: "0x495f947276749ce646f68ac8c248420045cb7b5e",
    creator_address: "0x438cba7e454b59a9f897d4731fd3eaef37160c0a",
    token:
      "30553606573219150352991292921105176340809048341686170040023897701179038105601",
    creator_name: "Darkblockio",
    image:
      "https://lh3.googleusercontent.com/7QXdchIPTWNQm--guaKHTX8KvUVxvTZz_sobraX_RpxWCfVWo9nR17Acb6W4yzG4t207ejMYQv4NRvZwwddjvcDOfUv9h8DjDOvvvg",
    is_darkblocked: true,
  },
  {
    name: "𝔊𝔥𝔬𝔰𝔱 26",
    description: "Don't be afraid. I'm a good ghost",
    contract: "KT1CMhjdDMUi9LEXMBpZ9htunf6SUtP1HeHU",
    creator_address: "tz1NvTU7yGsVKZn2svBXZDRkFEnBjq7yMbPj",
    token: "23",
    creator_name: "Tez Ghosts",
    image:
      "https://assets.objkt.media/file/assets-003/QmNPkZVDNLyZwX7ViDxN2Ek4cnSW4HCp9fm7EhbPZKMfe7/artifact",
    is_darkblocked: false,
  },
  {
    name: "𝔊𝔥𝔬𝔰𝔱 23",
    description: "Don't be afraid. I'm a good ghost",
    contract: "KT1CMhjdDMUi9LEXMBpZ9htunf6SUtP1HeHU",
    creator_address: "tz1NvTU7yGsVKZn2svBXZDRkFEnBjq7yMbPj",
    token: "22",
    creator_name: "Tez Ghosts",
    image:
      "https://assets.objkt.media/file/assets-003/QmaiPoDawTWfKcywuzvDoDgSrd5r5KsQzcuLVfmRMAEUft/artifact",
    is_darkblocked: false,
  },
  {
    name: "𝔊𝔥𝔬𝔰𝔱 22",
    description: "Don't be afraid. I'm a good ghost",
    contract: "KT1CMhjdDMUi9LEXMBpZ9htunf6SUtP1HeHU",
    creator_address: "tz1NvTU7yGsVKZn2svBXZDRkFEnBjq7yMbPj",
    token: "21",
    creator_name: "Tez Ghosts",
    image:
      "https://assets.objkt.media/file/assets-003/QmYyWboZn5hju4dbxQYNMDxrywdMo5yKrgFSWda4fCxrV2/artifact",
    is_darkblocked: false,
  },
  {
    name: "𝔊𝔥𝔬𝔰𝔱 18",
    description: "Don't be afraid. I'm a good ghost",
    contract: "KT1CMhjdDMUi9LEXMBpZ9htunf6SUtP1HeHU",
    creator_address: "tz1NvTU7yGsVKZn2svBXZDRkFEnBjq7yMbPj",
    token: "17",
    creator_name: "Tez Ghosts",
    image:
      "https://assets.objkt.media/file/assets-003/Qmd1mBSxPtoMP6qXfA8gzFAfR9KLR82LkrwKUDUa8w76Ps/artifact",
    is_darkblocked: false,
  },
  {
    name: "𝔊𝔥𝔬𝔰𝔱 16",
    description: "Don't be afraid. I'm a good ghost",
    contract: "KT1CMhjdDMUi9LEXMBpZ9htunf6SUtP1HeHU",
    creator_address: "tz1NvTU7yGsVKZn2svBXZDRkFEnBjq7yMbPj",
    token: "15",
    creator_name: "Tez Ghosts",
    image:
      "https://assets.objkt.media/file/assets-003/QmQqCYgV9dquN9s7mnWHMqLSf448RaZ1trYWiQeSv6P9sQ/artifact",
    is_darkblocked: false,
  },
];
